# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff949464663d8d0e756c156395dac142efdb86b10060c92d9fd08b80cb01277eaebd1d6723e2f601b9741a0363b3a9b5454be1d927dfb7303d019841e3e9166

test:
  secret_key_base: 4160d11c536e39758d6706b299d4ac1240c2008c78e5f8783de1868653f9672b085038fa43b5572cc817a669de2965870c9633e19c220d949fbfd28419ef7581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
