# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0ebccac5bb5c09da5df4d88c3ed35c9cafe2939bd907ed2adb1e803b55420536305b407687e1b07eeed824479e498245e481cec050df187003462637f1e50a9

test:
  secret_key_base: 2c0bd2d46d2cc3ad9d7b19a87a934ade54ec49c1be83b896b77c9b4eb9253aa36f0a02000efee5c74e2771aaeff11c6d3b0a19572c10aac0bd7c2f44a5ae1b99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
