# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3c7c1c45f0645fba5ef89a79be223d32dbe9c987b12ae063c952f81446c8f4c194174b3be2c83ce2c08e6031e7c1c4cd2e91fddc60bf653c0d480f3df56e250

test:
  secret_key_base: 57b22c398b201b65535d88b814cc743786028514a4043119fa977c4d6aef8d8a2957865ea873d87a1961a9a9865050c55112d7250eddc324298a281a71fc93d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
