# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cf702553de19d9ab39be72816912d867d58e81e975f3eb0798a2970d9ed531ab3747ba1d8e72aa8692dc6341fc0d86fe91668c15d230dc6314fa57e40805b4b

test:
  secret_key_base: 045ce1ac537222783087cf7e5dde9da7d4f5658205e2205f63d277345d1adbb9a3fca088946246a16dc8a12e94fab9899340dc8ff849a2abcdc5a5672bb530b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
