Choice.create(title: 'Would you rather know the... (death cannot be avoided by acting upon this knowledge)', description: '', option_a: 'Date of your death', option_b: 'Cause of your death')
Choice.create(title: 'Which Harry Potter spell would you like to use more?', description: '', option_a: 'Alohomora - unlocks locked things', option_b: 'Obliviate - Erases your or other people\'s memories')
Choice.create(title: 'Would you rather go back to', description: '', option_a: 'Ancient Greece', option_b: 'Ancient Rome')
Vote.create(selection: 'option_a', choice_id: 1)
Vote.create(selection: 'option_b', choice_id: 2)
Vote.create(selection: 'option_a', choice_id: 3)
